insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-02-14', 3, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-01-30', 17, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Offered', '2026-03-08', 7, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Rejected', '2026-02-22', 11, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-03-19', 24, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-02-05', 5, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Offered', '2026-01-18', 9, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Rejected', '2026-03-27', 2, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-02-11', 14, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-03-03', 20, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Offered', '2026-01-25', 6, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Rejected', '2026-02-17', 13, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-03-14', 28, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-01-21', 1, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Offered', '2026-02-28', 16, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Rejected', '2026-03-06', 22, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-01-14', 8, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-02-09', 31, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Offered', '2026-03-21', 4, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Rejected', '2026-01-31', 19, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-02-24', 33, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-03-10', 10, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Offered', '2026-01-16', 25, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Rejected', '2026-02-20', 35, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-03-25', 12, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-01-28', 27, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Offered', '2026-02-15', 18, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Rejected', '2026-03-01', 30, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-02-07', 21, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-01-23', 34, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Offered', '2026-03-17', 15, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Rejected', '2026-02-03', 26, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-03-29', 23, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-01-11', 32, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Offered', '2026-02-26', 29, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-03-12', 7, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-02-18', 3, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Offered', '2026-01-29', 20, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Rejected', '2026-03-04', 14, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-02-13', 9, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-03-22', 5, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Offered', '2026-01-17', 28, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Rejected', '2026-02-06', 1, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-03-16', 17, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-01-26', 11, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Offered', '2026-02-21', 24, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Rejected', '2026-03-08', 33, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-01-13', 6, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-02-27', 13, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Offered', '2026-03-20', 22, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Rejected', '2026-01-20', 35, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-02-16', 8, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-03-11', 19, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Offered', '2026-01-22', 30, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Rejected', '2026-02-10', 16, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-03-26', 25, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-01-15', 31, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Offered', '2026-02-23', 4, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Rejected', '2026-03-05', 12, 2);
insert into Applications (status, deadline, listingId, studentId) values ('Pending', '2026-01-19', 27, 1);
insert into Applications (status, deadline, listingId, studentId) values ('Interviewing', '2026-02-08', 2, 2);

insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-02-10 09:15:00', 'Software Engineer Co-op', 17, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-02-13 14:00:00', 'Data Analyst Co-op', 2, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-02-17 10:30:00', 'Machine Learning Co-op', 5, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-02-19 13:45:00', 'DevOps Co-op', 6, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-02-21 09:00:00', 'Cloud Engineering Co-op', 10, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-02-24 11:00:00', 'Cybersecurity Co-op', 9, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-02-26 15:30:00', 'Full Stack Developer Co-op', 18, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-03-02 10:00:00', 'Data Science Co-op', 20, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-03-05 13:00:00', 'Frontend Developer Co-op', 3, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-03-09 09:30:00', 'Backend Developer Co-op', 4, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-03-11 14:15:00', 'iOS Developer Co-op', 11, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-03-14 11:00:00', 'QA Engineer Co-op', 7, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-03-16 10:45:00', 'Site Reliability Co-op', 21, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-03-18 13:30:00', 'AI Research Co-op', 24, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-03-20 09:00:00', 'Platform Engineering Co-op', 22, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-03-23 14:00:00', 'Finance Technology Co-op', 25, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-03-25 10:30:00', 'Data Engineer Co-op', 17, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-03-27 15:00:00', 'Android Developer Co-op', 12, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-03-30 09:15:00', 'Business Intelligence Co-op', 13, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-04-01 11:45:00', 'Security Analyst Co-op', 19, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-04-03 13:00:00', 'Network Engineering Co-op', 23, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-04-07 10:00:00', 'Growth Engineering Co-op', 30, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-04-09 14:30:00', 'Software Engineer Co-op', 26, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-04-11 09:45:00', 'Embedded Systems Co-op', 31, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-04-14 11:00:00', 'Database Engineering Co-op', 32, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-04-16 13:15:00', 'Mobile Developer Co-op', 28, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-04-18 10:00:00', 'Infrastructure Co-op', 29, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-04-21 14:00:00', 'Compiler Engineering Co-op', 33, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-04-23 09:30:00', 'Blockchain Co-op', 34, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-04-25 11:30:00', 'AR/VR Developer Co-op', 35, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-04-28 13:00:00', 'Product Manager Co-op', 8, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-04-30 10:15:00', 'Technical Writing Co-op', 15, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-05-02 14:45:00', 'UX Research Co-op', 14, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-05-05 09:00:00', 'Data Analyst Co-op', 27, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-05-07 11:00:00', 'Software Engineer Co-op', 1, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-05-09 13:30:00', 'Data Science Co-op', 20, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-05-12 10:00:00', 'Cloud Engineering Co-op', 10, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-05-14 14:00:00', 'Backend Developer Co-op', 4, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-05-16 09:15:00', 'Machine Learning Co-op', 5, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-05-19 11:45:00', 'Full Stack Developer Co-op', 18, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-05-21 13:00:00', 'DevOps Co-op', 6, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-05-23 10:30:00', 'iOS Developer Co-op', 11, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-05-26 14:15:00', 'Frontend Developer Co-op', 3, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-05-28 09:00:00', 'Cybersecurity Co-op', 9, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-05-30 11:00:00', 'QA Engineer Co-op', 7, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-06-02 13:45:00', 'Site Reliability Co-op', 21, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-06-04 10:00:00', 'AI Research Co-op', 24, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-06-06 14:30:00', 'Platform Engineering Co-op', 22, 2, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-06-09 09:30:00', 'Network Engineering Co-op', 23, 1, 1);
insert into Interviews (headInterviewerFullName, headInterviewerEmail, dateTime, position, listingId, studentId, companyId) values ('Thiago Goat', 'tgoat@acmecorp.com', '2026-06-11 11:15:00', 'Finance Technology Co-op', 25, 2, 1);

insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (32, 'Accepted', 3, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (26, 'Rejected', 7, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (34, 'Accepted', 11, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (25, 'Pending', 15, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (30, 'Accepted', 19, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (29, 'Rejected', 23, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (27, 'Accepted', 27, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (31, 'Pending', 31, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (33, 'Accepted', 35, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (28, 'Rejected', 39, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (26, 'Accepted', 43, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (30, 'Pending', 47, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (24, 'Accepted', 51, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (32, 'Rejected', 55, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (29, 'Accepted', 59, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (31, 'Pending', 4, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (28, 'Accepted', 8, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (25, 'Rejected', 12, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (33, 'Accepted', 16, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (27, 'Pending', 20, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (30, 'Accepted', 24, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (26, 'Rejected', 28, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (34, 'Accepted', 32, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (29, 'Pending', 36, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (31, 'Accepted', 40, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (28, 'Rejected', 44, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (32, 'Accepted', 48, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (25, 'Pending', 52, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (27, 'Accepted', 56, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (30, 'Rejected', 60, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (29, 'Accepted', 3, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (33, 'Pending', 7, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (26, 'Accepted', 11, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (31, 'Rejected', 15, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (28, 'Accepted', 19, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (30, 'Pending', 23, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (25, 'Accepted', 27, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (34, 'Rejected', 31, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (27, 'Accepted', 35, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (32, 'Pending', 39, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (29, 'Accepted', 43, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (26, 'Rejected', 47, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (31, 'Accepted', 51, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (28, 'Pending', 55, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (33, 'Accepted', 59, 2);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (27, 'Rejected', 4, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (30, 'Accepted', 8, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (34, 'Pending', 12, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (26, 'Accepted', 16, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (29, 'Rejected', 20, 1);
insert into Offers (finalSalary, acceptanceStatus, applicationId, studentId) values (31, 'Accepted', 24, 1);
