USE `Coop-Scoop`;

INSERT INTO Companies (companyName, location, website, searching)
VALUES
    ('Google', '355 Main St, Cambridge, MA', 'https://google.com', TRUE),
    ('Microsoft', '1 Memorial Dr, Cambridge, MA', 'https://microsoft.com', TRUE),
    ('Amazon', '100 Causeway St, Boston, MA', 'https://amazon.com', TRUE),
    ('Meta', '100 Binney St, Cambridge, MA', 'https://meta.com', TRUE),
    ('Apple', '33 Boylston St, Boston, MA', 'https://apple.com', TRUE),
    ('Wayfair', '4 Copley Pl, Boston, MA', 'https://wayfair.com', TRUE),
    ('HubSpot', '2 Canal St, Cambridge, MA', 'https://hubspot.com', TRUE),
    ('DraftKings', '222 Berkeley St, Boston, MA', 'https://draftkings.com', TRUE),
    ('Akamai', '145 Broadway, Cambridge, MA', 'https://akamai.com', TRUE),
    ('Fidelity Investments', '245 Summer St, Boston, MA', 'https://fidelity.com', TRUE),
    ('Vertex Pharmaceuticals', '50 Northern Ave, Boston, MA', 'https://vrtx.com', TRUE),
    ('Moderna', '200 Technology Square, Cambridge, MA', 'https://modernatx.com', TRUE),
    ('Biogen', '225 Binney St, Cambridge, MA', 'https://biogen.com', TRUE),
    ('Tripadvisor', '400 1st Ave, Needham, MA', 'https://tripadvisor.com', TRUE),
    ('IBM', '75 Binney St, Cambridge, MA', 'https://ibm.com', TRUE),
    ('Salesforce', '125 High St, Boston, MA', 'https://salesforce.com', TRUE),
    ('Oracle', '470 Atlantic Ave, Boston, MA', 'https://oracle.com', TRUE),
    ('Uber', '100 Summer St, Boston, MA', 'https://uber.com', TRUE),
    ('Spotify', '101 Seaport Blvd, Boston, MA', 'https://spotify.com', FALSE),
    ('CarGurus', '2 Canal St, Cambridge, MA', 'https://cargurus.com', TRUE),
    ('Toast', '401 Park Dr, Boston, MA', 'https://toasttab.com', FALSE),
    ('LogMeIn (GoTo)', '333 Summer St, Boston, MA', 'https://goto.com', TRUE),
    ('Rapid7', '100 Causeway St, Boston, MA', 'https://rapid7.com', TRUE),
    ('CyberArk', '60 Wells Ave, Newton, MA', 'https://cyberark.com', TRUE),
    ('PTC', '121 Seaport Blvd, Boston, MA', 'https://ptc.com', TRUE),
    ('Boston Dynamics', '200 Smith St, Waltham, MA', 'https://bostondynamics.com', TRUE),
    ('iRobot', '8 Crosby Dr, Bedford, MA', 'https://irobot.com', TRUE),
    ('Nuance Communications', '1 Wayside Rd, Burlington, MA', 'https://nuance.com', TRUE),
    ('Formlabs', '35 Medford St, Somerville, MA', 'https://formlabs.com', TRUE),
    ('Indigo Ag', '500 Rutherford Ave, Charlestown, MA', 'https://indigoag.com', TRUE),
    ('DataRobot', '225 Franklin St, Boston, MA', 'https://datarobot.com', TRUE),
    ('Drizly', '177 Milk St, Boston, MA', 'https://drizly.com', TRUE),
    ('Klaviyo', '125 High St, Boston, MA', 'https://klaviyo.com', TRUE),
    ('Lola.com', '175 Federal St, Boston, MA', 'https://lola.com', TRUE),
    ('Recorded Future', '363 Highland Ave, Somerville, MA', 'https://recordedfuture.com', TRUE),
    ('Starry', '38 Chauncy St, Boston, MA', 'https://starry.com', TRUE),
    ('Tamr', '66 Church St, Cambridge, MA', 'https://tamr.com', TRUE),
    ('VMTurbo (Turbonomic)', '500 Totten Pond Rd, Waltham, MA', 'https://turbonomic.com', TRUE),
    ('Salsify', '101 Federal St, Boston, MA', 'https://salsify.com', TRUE),
    ('Flywire', '141 Tremont St, Boston, MA', 'https://flywire.com', TRUE),
    ('BlackDuck', '8 New England Executive Park, Burlington, MA', 'https://blackducksoftware.com', TRUE),
    ('Acquia', '53 State St, Boston, MA', 'https://acquia.com', TRUE),
    ('CloudLock', '200 Second St, Cambridge, MA', 'https://cloudlock.com', TRUE),
    ('SimpliSafe', '224 Summer St, Boston, MA', 'https://simplisafe.com', TRUE),
    ('SmartBear', '450 Artisan Way, Somerville, MA', 'https://smartbear.com', FALSE),
    ('Mimecast', '100 Hayden Ave, Lexington, MA', 'https://mimecast.com', TRUE),
    ('Carbon Black', '1100 Winter St, Waltham, MA', 'https://carbonblack.com', TRUE),
    ('Pegasystems', '1 Main St, Cambridge, MA', 'https://pega.com', TRUE),
    ('Progress Software', '15 Wayside Rd, Burlington, MA', 'https://progress.com', TRUE);


INSERT INTO Recruiters (userId, firstName, lastName, companyId)
VALUES
    (1000096, 'Sarah', 'Miller', 3),
    (1000002, 'Michael', 'Wilson', 46),
    (1000092, 'Emily', 'Moore', 33),
    (1000082, 'David', 'Taylor', 33),
    (1000001, 'Jessica', 'Anderson', 15),
    (1000059, 'Chris', 'Thomas', 45),
    (1000018, 'Ashley', 'Jackson', 17),
    (1000145, 'Matthew', 'White', 2),
    (1000106, 'Amanda', 'Harris', 35),
    (1000136, 'Joshua', 'Martin', 12),
    (1000057, 'Jennifer', 'Thompson', 32),
    (1000035, 'Daniel', 'Garcia', 13),
    (1000026, 'Taylor', 'Martinez', 5),
    (1000174, 'James', 'Robinson', 18),
    (1000123, 'Megan', 'Clark', 45),
    (1000014, 'Robert', 'Rodriguez', 23),
    (1000028, 'Lauren', 'Lewis', 36),
    (1000029, 'Joseph', 'Lee', 28),
    (1000055, 'Nicole', 'Walker', 10),
    (1000020, 'Andrew', 'Hall', 32);

