USE coop_scoop;

SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO Reviews (content, rating, position, anonymous, approval, studentId, companyId, cycleId, adminId)
VALUES
    ('Tough interview process but worth it. The office in Boston is awesome.', 3, 'Backend Engineering Co-op', FALSE, 'Approved', 91, 39, 10, 12),
    ('Decent co-op. A bit slow at first but got to work on some cool features by the end. Free snacks were a plus.', 4, 'Machine Learning Intern', FALSE, 'Approved', 101, 50, 11, 11),
    ('It was okay. A lot of legacy code and meetings, but I definitely leveled up my debugging skills.', 3, 'Full Stack Developer', TRUE, 'Approved', 23, 17, 10, 7),
    ('AABFJSDKFJBSKDFJBSKDJBFKSDJFBKSDJBF', 4, 'Product Management Intern', TRUE, 'Rejected', 7, 4, 8, 3),
    ('It was okay. A lot of legacy code and meetings, but I definitely leveled up my debugging skills.', 4, 'Mobile Dev Intern', FALSE, 'Approved', 6, 67, 3, 1),
    ('The internship was mostly remote which was nice but it was hard to get help sometimes.', 5, 'Full Stack Developer', TRUE, 'Approved', 17, 10, 12, 5),
    ('Good place to learn but the workload is pretty heavy. Hard to maintain work-life balance sometimes.', 5, 'Cloud Engineer Co-op', TRUE, 'Approved', 52, 21, 4, 4),
    ('It was okay. A lot of legacy code and meetings, but I definitely leveled up my debugging skills.', 4, 'QA Analyst', TRUE, 'Pending', 53, 13, 12, 11),
    ('Amazing culture and the mentorship was top tier. Highly recommend applying if you like fast-paced environments.', 3, 'Machine Learning Intern', FALSE, 'Pending', 34, 47, 13, 13),
    ('Decent co-op. A bit slow at first but got to work on some cool features by the end. Free snacks were a plus.', 4, 'Backend Engineering Co-op', FALSE, 'Approved', 69, 45, 13, 18),
    ('Felt a bit lost because my manager was always busy, but the other interns were great.', 4, 'Software Engineering Intern', TRUE, 'Pending', 41, 49, 6, 20),
    ('Amazing culture and the mentorship was top tier. Highly recommend applying if you like fast-paced environments.', 4, 'Cloud Engineer Co-op', FALSE, 'Approved', 102, 32, 13, 4),
    ('Tough interview process but worth it. The office in Boston is awesome.', 5, 'Cloud Engineer Co-op', FALSE, 'Approved', 109, 1, 4, 19),
    ('Great intro to the industry. Managed to push code to production in my first month!', 3, 'Software Engineering Intern', TRUE, 'Approved', 113, 2, 6, 11),
    ('Loved it here! Everyone was so smart and willing to help. Definitely felt like a valued member of the team.', 4, 'Machine Learning Intern', TRUE, 'Pending', 51, 2, 5, 5),
    ('Felt a bit lost because my manager was always busy, but the other interns were great.', 5, 'Machine Learning Intern', TRUE, 'Pending', 65, 3, 4, 8),
    ('Decent co-op. A bit slow at first but got to work on some cool features by the end. Free snacks were a plus.', 3, 'Frontend Developer', FALSE, 'Pending', 62, 27, 7, 19),
    ('Solid experience. Learned a ton about Kubernetes. The team was super supportive, though the pay could be better.', 3, 'Mobile Dev Intern', FALSE, 'Approved', 5, 47, 11, 10),
    ('Amazing culture and the mentorship was top tier. Highly recommend applying if you like fast-paced environments.', 5, 'Software Engineering Intern', TRUE, 'Approved', 8, 4, 11, 16),
    ('It was okay. A lot of legacy code and meetings, but I definitely leveled up my debugging skills.', 3, 'Cloud Engineer Co-op', FALSE, 'Pending', 48, 43, 9, 17),
    ('Tough interview process but worth it. The office in Boston is awesome.', 3, 'Machine Learning Intern', FALSE, 'Rejected', 74, 26, 3, 3),
    ('Decent co-op. A bit slow at first but got to work on some cool features by the end. Free snacks were a plus.', 3, 'Cloud Engineer Co-op', FALSE, 'Pending', 77, 50, 9, 17),
    ('TERRIBLE TERRIBLE TERRIBLE TERRIBLE TERRIBLE', 5, 'QA Analyst', FALSE, 'Rejected', 80, 146, 13, 14),
    ('It was okay. A lot of legacy code and meetings, but I definitely leveled up my debugging skills.', 3, 'Frontend Developer', TRUE, 'Approved', 83, 35, 9, 7),
    ('Solid experience. Learned a ton about React. The team was super supportive, though the pay could be better.', 3, 'Machine Learning Intern', FALSE, 'Approved', 19, 18, 11, 1),
    ('Decent co-op. A bit slow at first but got to work on some cool features by the end. Free snacks were a plus.', 5, 'Backend Engineering Co-op', FALSE, 'Approved', 4, 8, 12, 14),
    ('The internship was mostly remote which was nice but it was hard to get help sometimes.', 5, 'Product Management Intern', TRUE, 'Approved', 60, 44, 1, 7),
    ('It was okay. A lot of legacy code and meetings, but I definitely leveled up my debugging skills.', 5, 'Machine Learning Intern', FALSE, 'Pending', 42, 32, 12, 8),
    ('Decent co-op. A bit slow at first but got to work on some cool features by the end. Free snacks were a plus.', 3, 'Cloud Engineer Co-op', FALSE, 'Approved', 115, 20, 12, 16),
    ('Good place to learn but the workload is pretty heavy. Hard to maintain work-life balance sometimes.', 4, 'Machine Learning Intern', TRUE, 'Pending', 15, 32, 3, 15),
    ('Decent co-op. A bit slow at first but got to work on some cool features by the end. Free snacks were a plus.', 4, 'Machine Learning Intern', TRUE, 'Approved', 57, 14, 11, 7),
    ('Great intro to the industry. Managed to push code to production in my first month!', 5, 'Product Management Intern', TRUE, 'Pending', 13, 46, 8, 3),
    ('Solid experience. Learned a ton about React. The team was super supportive, though the pay could be better.', 3, 'QA Analyst', TRUE, 'Approved', 111, 33, 9, 5),
    ('Solid experience. Learned a ton about React. The team was super supportive, though the pay could be better.', 4, 'Mobile Dev Intern', FALSE, 'Approved', 46, 38, 11, 8),
    ('Good place to learn but the workload is pretty heavy. Hard to maintain work-life balance sometimes.', 4, 'Software Engineering Intern', TRUE, 'Approved', 92, 39, 12, 4),
    ('Decent co-op. A bit slow at first but got to work on some cool features by the end. Free snacks were a plus.', 3, 'Product Management Intern', FALSE, 'Approved', 73, 50, 8, 8),
    ('Solid experience. Learned a ton about React. The team was super supportive, though the pay could be better.', 4, 'Frontend Developer', FALSE, 'Approved', 16, 3, 13, 10),
    ('Loved it here! Everyone was so smart and willing to help. Definitely felt like a valued member of the team.', 3, 'Frontend Developer', TRUE, 'Approved', 32, 41, 7, 3),
    ('Good place to learn but the workload is pretty heavy. Hard to maintain work-life balance sometimes.', 5, 'Machine Learning Intern', FALSE, 'Pending', 61, 1, 2, 20),
    ('Solid experience. Learned a ton about TypeScript. The team was super supportive, though the pay could be better.', 3, 'QA Analyst', FALSE, 'Approved', 78, 34, 13, 14),
    ('Loved it here! Everyone was so smart and willing to help. Definitely felt like a valued member of the team.', 3, 'Mobile Dev Intern', FALSE, 'Approved', 10, 22, 10, 17),
    ('It was okay. A lot of legacy code and meetings, but I definitely leveled up my debugging skills.', 3, 'Data Science Co-op', TRUE, 'Pending', 99, 84, 13, 15),
    ('HIHIHIHIHIIHIHIHIHIHI HELLO!!!!!! HI!', 4, 'Machine Learning Intern', FALSE, 'Rejected', 82, 92, 10, 14),
    ('Good place to learn but the workload is pretty heavy. Hard to maintain work-life balance sometimes.', 5, 'Frontend Developer', TRUE, 'Approved', 89, 7, 13, 9),
    ('Decent co-op. A bit slow at first but got to work on some cool features by the end. Free snacks were a plus.', 5, 'Data Science Co-op', TRUE, 'Approved', 84, 26, 11, 5),
    ('Decent co-op. A bit slow at first but got to work on some cool features by the end. Free snacks were a plus.', 4, 'Mobile Dev Intern', TRUE, 'Approved', 66, 15, 13, 9),
    ('Good place to learn but the workload is pretty heavy. Hard to maintain work-life balance sometimes.', 5, 'Data Science Co-op', TRUE, 'Approved', 18, 7, 12, 17),
    ('Felt a bit lost because my manager was always busy, but the other interns were great.', 3, 'Data Science Co-op', TRUE, 'Approved', 63, 9, 10, 15),
    ('Solid experience. Learned a ton about SQL. The team was super supportive, though the pay could be better.', 4, 'Mobile Dev Intern', TRUE, 'Approved', 104, 6, 12, 13),
    ('Loved it here! Everyone was so smart and willing to help. Definitely felt like a valued member of the team.', 3, 'Data Science Co-op', FALSE, 'Approved', 64, 26, 8, 8);

SET FOREIGN_KEY_CHECKS = 1;
